### ISSUE TITLE
runtime error: XXX is not a function

### ISSUE THREAD

**Issue by MastroLindus** [ref-app/meteor-typescript-compiler#1]
Hi,

first of all, thank you again for your contribution to meteor and typescript with this package!

As promised, I gave it a spin. 
I can see the compilation output for all meteor's targets (web, legacy, server).
After that and the start of mongoDB, I see an error:

```
W20200526-09:30:53.657(0)? (STDERR) /home/mastro/.meteor/packages/meteor-tool/.1.9.2.bqo92k.42r5q++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20200526-09:30:53.668(0)? (STDERR)                                             throw(ex);
W20200526-09:30:53.669(0)? (STDERR)                                             ^
W20200526-09:30:53.669(0)? (STDERR) 
W20200526-09:30:53.669(0)? (STDERR) TypeError: validationUtils_1.SecuredMethod is not a function
W20200526-09:30:53.669(0)? (STDERR)     at module (imports/api/YYY/server/methods.ts:31:30)
W20200526-09:30:53.669(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20200526-09:30:53.669(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20200526-09:30:53.670(0)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20200526-09:30:53.670(0)? (STDERR)     at module (imports/api/server/validationUtils.ts:8:1)
W20200526-09:30:53.670(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20200526-09:30:53.670(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20200526-09:30:53.670(0)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20200526-09:30:53.670(0)? (STDERR)     at module (imports/api/menuTranslations/server/methods.ts:4:1)
W20200526-09:30:53.670(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20200526-09:30:53.670(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20200526-09:30:53.671(0)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20200526-09:30:53.671(0)? (STDERR)     at module (imports/api/XXX/server/methods.ts:3:1)
W20200526-09:30:53.671(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20200526-09:30:53.671(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20200526-09:30:53.671(0)? (STDERR)     at require (packages/modules-runtime.js:258:21)
```

That validationUtils_1.SecuredMethod   is simply a wrapper we use around mdg:validated-method, it is used to declare all our methods and it is simply something like this:

```
export function SecuredMethod(
// some extra params/generics
) {
const newOptions = {// some options };
  return new ValidatedMethod(newOptions);
}
```

and used like: 
```
import { SecuredMethod } from "../../server/validationUtils";

export const myMethod = SecuredMethod({
// options
});
```

It works fine with adornis, barbatus and the official meteor ts plugin, so I guess it is something related to the incremental compilation used by this one? maybe some circular dependency that building all modules at once doesn't handle?

**Comment by perbergland** [comment]
Nothing obvious comes to mind.

Please check into the generated code in .meteor/local/build/programs/server/app/app.js for two variants (e.g. builtin vs this compiler) and see if you can make sense of the different outputs. 

That’s where all your app code goes after transpilation.

**Comment by MastroLindus** [comment]
After checking the output I realized that the main difference was the module type (in my tsconfig.json I still had module: "commonjs" from when I used to work with barbatus-like plugins, as it was working correctly back then). Not really sure what the official typescript package uses but I know it bypass that setting in the tsconfig.json anyway.

I switched to es6 and now it is working correctly. 
Not sure why commonjs doesn't work anymore, as it used to, but I don't really mind switching.

I know it's a bit out of scope for this issue, but might I ask you if compared to the official plugin in your experience this is faster? To me unfortunately feels much slower, even if I didn't do any benchmarks. Probably it is because the official one doesn't type-check anything?

**Comment by perbergland** [comment]
Yeah I only tested with what is hardcoded in the offical compiler (module & target = "esnext") because I suspect the babel settings in meteor-babel only work properly with those compiler settings.

https://github.com/meteor/babel/blob/a7301c6e3138c54608946bd5407c1270371c2860/index.js#L147

As for speed, no I never did benchmark but I wouldn’t be surprised if the global type checking  incurs a significant cost.

**Comment by perbergland** [comment]
btw I'm removing issues from this project now so they can be filed in the "main" project
